id_78:
  entry: "Started GET \"/users/sign_in\" for 61.21.7.68 at 2013-06-02 13:11:30 +0000\nProcessing by SessionsController#new as HTML\nFilter chain halted as :basic_auth rendered or redirected\nCompleted 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)\n"
  timestamp:
    - '2013-06-02 13:11:30 +0000'
  error_status: '401'
  environment: production
id_79:
  entry: "Started GET \"/questionnaires/18/questions/new\" for 61.119.89.245 at 2013-06-03 00:49:43 +0000\nProcessing by QuestionsController#new as HTML\n  Parameters: {\"questionnaire_id\"=>\"18\"}\nCompleted 401 Unauthorized in 1ms\n"
  timestamp:
    - '2013-06-03 00:49:43 +0000'
  error_status: '401'
  environment: production
id_80:
  entry: "Started GET \"/users/sign_in\" for 61.119.89.245 at 2013-06-03 00:49:43 +0000\nProcessing by SessionsController#new as HTML\nFilter chain halted as :basic_auth rendered or redirected\nCompleted 401 Unauthorized in 0ms (ActiveRecord: 0.0ms)\n"
  timestamp:
    - '2013-06-03 00:49:43 +0000'
  error_status: '401'
  environment: production
id_81:
  entry: "Started GET \"/questions/781/edit\" for 61.119.89.243 at 2013-06-03 00:58:09 +0000\nProcessing by QuestionsController#edit as HTML\n  Parameters: {\"id\"=>\"781\"}\nCompleted 404 Not Found in 12ms\n\nActiveRecord::RecordNotFound (Couldn't find Question with id=781 [WHERE `questions`.`inbox_id` = 7]):\n  app/controllers/questions_controller.rb:49:in `edit'\n  app/controllers/application_controller.rb:38:in `scope_current_inbox'\n\n\n"
  timestamp:
    - '2013-06-03 00:58:09 +0000'
  error_status: '404'
  environment: production
id_82:
  entry: "Started GET \"/questions/781/edit\" for 61.119.89.243 at 2013-06-03 00:58:15 +0000\nProcessing by QuestionsController#edit as HTML\n  Parameters: {\"id\"=>\"781\"}\nCompleted 404 Not Found in 12ms\n\nActiveRecord::RecordNotFound (Couldn't find Question with id=781 [WHERE `questions`.`inbox_id` = 7]):\n  app/controllers/questions_controller.rb:49:in `edit'\n  app/controllers/application_controller.rb:38:in `scope_current_inbox'\n\n\n"
  timestamp:
    - '2013-06-03 00:58:15 +0000'
  error_status: '404'
  environment: production
id_83:
  entry: "Started GET \"/questions/781/edit\" for 61.119.89.243 at 2013-06-03 00:58:17 +0000\nProcessing by QuestionsController#edit as HTML\n  Parameters: {\"id\"=>\"781\"}\nCompleted 404 Not Found in 12ms\n\nActiveRecord::RecordNotFound (Couldn't find Question with id=781 [WHERE `questions`.`inbox_id` = 7]):\n  app/controllers/questions_controller.rb:49:in `edit'\n  app/controllers/application_controller.rb:38:in `scope_current_inbox'\n\n\n"
  timestamp:
    - '2013-06-03 00:58:17 +0000'
  error_status: '404'
  environment: production
id_84:
  entry: "Started GET \"/questionnaires/18/questions/new\" for 117.55.68.182 at 2013-06-03 01:09:58 +0000\nProcessing by QuestionsController#new as HTML\n  Parameters: {\"questionnaire_id\"=>\"18\"}\nCompleted 401 Unauthorized in 1ms\n"
  timestamp:
    - '2013-06-03 01:09:58 +0000'
  error_status: '401'
  environment: production
id_85:
  entry: "Started GET \"/users/sign_in\" for 117.55.68.182 at 2013-06-03 01:09:58 +0000\nProcessing by SessionsController#new as HTML\nFilter chain halted as :basic_auth rendered or redirected\nCompleted 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)\n"
  timestamp:
    - '2013-06-03 01:09:58 +0000'
  error_status: '401'
  environment: production
id_86:
  entry: "Started GET \"/users/sign_in\" for 61.119.89.244 at 2013-06-03 02:27:48 +0000\nProcessing by SessionsController#new as HTML\nFilter chain halted as :basic_auth rendered or redirected\nCompleted 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)\n"
  timestamp:
    - '2013-06-03 02:27:48 +0000'
  error_status: '401'
  environment: production
